Repository rajan123456/uPresent, pull requests merged in 2020-03, with the labels that each got.

#55 no description swagger+ updated readme
  attendance/Pipfile
  attendance/Pipfile.lock
  attendance/README.md
  attendance/app.py
  attendance/requirements.txt
  attendance/resources/attendance.py
Labels: enhancement

#56 Module registration
  management/src/main/java/com/upresent/management/controller/AdminModuleController.java
  management/src/main/java/com/upresent/management/service/AdminModuleService.java
  management/src/main/java/com/upresent/management/service/AdminModuleServiceImpl.java
  management/src/main/java/com/upresent/management/utils/Constant.java
Labels: enhancement

#57 KeyChain Migration and Header Bug Fix
  uPresent/app/config/config.js
  uPresent/app/sections/Header.js
  uPresent/app/views/Login.js
  uPresent/package.json
  uPresent/yarn.lock
Labels: bug, enhancement

#60 Migrate to New Dev Box and Deployment Keys
  .travis.yml
  iss-dev-upresent.pem.enc
  uPresent/app/config/config.js
  upresent-admin/src/config/config.js
Labels: dev-ops

#37 Video Processor - Initial
  .gitignore
  .travis.yml
  scripts/dev/docker-compose.yml
  videoprocessor/.gitignore
  videoprocessor/Dockerfile
  videoprocessor/Pipfile
  videoprocessor/Pipfile.lock
  videoprocessor/app.py
  videoprocessor/config.py
  videoprocessor/requirements.txt
  videoprocessor/resources/inputData/example.mp4
  videoprocessor/resources/routes.py
  videoprocessor/resources/videoProcessor.py
  videoprocessor/resources/videoSplitter.py
Labels: enhancement

#66 Integrate Attendance Service with Vault
  .travis.yml
  attendance/.dockerignore
  attendance/.gitignore
  attendance/app.py
  attendance/attendance.pem.enc
  attendance/config.py
  attendance/key.pem.enc
  attendance/resources/attendance.py
  attendance/resources/rekognition.py
  attendance/resources/vault.py
  scripts/dev/.gitignore
  scripts/dev/docker-compose.yml
  scripts/dev/vault-data-vol/config/vault.json
Labels: in-progress
