Repository rajan123456/uPresent, pull requests merged in 2020-04, with the labels that each got.

#70 Fix bug in Fence.radiusInMeter
  upresent-admin/src/components/fences/CreateFenceForm.js
  upresent-admin/src/components/fences/CreateFencesPage.js
  upresent-admin/src/components/fences/FenceList.js
  upresent-admin/src/components/fences/ManageFenceForm.js
  upresent-admin/src/components/fences/ManageFencesPage.js
Labels: bug

#72 Add Username to Manage Fence Request
  upresent-admin/src/components/fences/CreateFencesPage.js
  upresent-admin/src/components/fences/ManageFencesPage.js
Labels: bug

#77 Management Bug Fix
  management/src/main/java/com/upresent/management/controller/AdminModuleController.java
Labels: bug

#78 Management: Allow modules with no students enrolled
  management/src/main/java/com/upresent/management/exception/ExceptionResponseCode.java
  management/src/main/java/com/upresent/management/service/AdminModuleServiceImpl.java
Labels: bug

#82 CORS Whitelist Username Header
  management/src/main/java/com/upresent/management/cors/CorsFilterImplementation.java
  management/src/main/java/com/upresent/management/service/AdminModuleServiceImpl.java
Labels: bug

#84 Add absenty students details
  reporting/src/main/java/com/upresent/reporting/service/AttendanceServiceImpl.java
Labels: bug

#88 Dev Box Migration and Reverse Proxy Initial
  .travis.yml
  scripts/dev/docker-compose.yml
  scripts/dev/filebeat-data-vol/filebeat.yml
  scripts/dev/init-letsencrypt.sh
  scripts/dev/metricbeat-data-vol/metricbeat.yml
  scripts/dev/proxy-data-nginx/nginx/app.conf
  uPresent/app/config/config.js
  upresent-admin/src/config/config.js
Labels: dev-ops, enhancement

#93 Update VideoProcessor to use SRS container
  videoprocessor/config.py
Labels: bug

#96 Deprecate Metrics Service
  .travis.yml
  metrics/.gitignore
  metrics/.mvn/wrapper/MavenWrapperDownloader.java
  metrics/.mvn/wrapper/maven-wrapper.jar
  metrics/.mvn/wrapper/maven-wrapper.properties
  metrics/Dockerfile
  metrics/mvnw
  metrics/mvnw.cmd
  metrics/pom.xml
  metrics/src/main/java/com/upresent/metrics/MetricsApplication.java
  metrics/src/main/java/com/upresent/metrics/controller/MetricsController.java
  metrics/src/main/java/com/upresent/metrics/entity/MetricsData.java
  metrics/src/main/java/com/upresent/metrics/exception/ExceptionResponseCode.java
  metrics/src/main/java/com/upresent/metrics/exception/MetricsException.java
  metrics/src/main/java/com/upresent/metrics/exception/RestExceptionHandler.java
  metrics/src/main/java/com/upresent/metrics/repository/MetricsRepository.java
  metrics/src/main/java/com/upresent/metrics/service/MetricsService.java
  metrics/src/main/java/com/upresent/metrics/service/MetricsServiceImpl.java
  metrics/src/main/java/com/upresent/metrics/subscriber/KafkaReceiver.java
  metrics/src/main/java/com/upresent/metrics/subscriber/KafkaReceiverConfig.java
  metrics/src/main/java/com/upresent/metrics/utils/AspectLogging.java
  metrics/src/main/java/com/upresent/metrics/utils/CommonUtility.java
  metrics/src/main/java/com/upresent/metrics/utils/Constant.java
  metrics/src/main/java/com/upresent/metrics/utils/RestResponse.java
  metrics/src/main/java/com/upresent/metrics/utils/RestUtils.java
  metrics/src/main/resources/application.properties
  metrics/src/test/java/com/upresent/metrics/MetricsApplicationTests.java
  scripts/dev/docker-compose.yml
Labels: invalid

#103 Multiple Bug Fixes
  attendance/resources/attendance.py
  attendance/resources/vault.py
  uPresent/app/views/Attendance.js
  upresent-admin/src/components/users/ManageUsersPage.js
  upresent-admin/src/components/users/UsersPage.js
Labels: bug

#123 AdminUI: Enroll only active students
  upresent-admin/src/components/modules/CreateModulesPage.js
  upresent-admin/src/components/modules/ManageModulesPage.js
Labels: bug

#128 VideoProcessor, StreamProcessor: Environment Variables and Documentation
  docs/StreamProcessor.jpg
  docs/VideoProcessor(1).jpg
  streamProcessor/README.md
  videoprocessor/README.md
  videoprocessor/app.py
  videoprocessor/resources/videoSplitter.py
Labels: documentation, in-progress

#133 SRS: Add VHost and HTTP RawAPI
  scripts/dev/srs-conf-vol/srs.conf
Labels: enhancement
